<script lang="ts">
	import { afterUpdate, createEventDispatcher, getContext, onMount } from 'svelte';
	import ChartCardCanvas from './ChartCardCanvas.svelte';
	import { isNearBottom, scrollToBottom } from './scroll-utils';
	import { workspaceEvents } from '$lib/stores/data-analysis';

	export let messages = [];
	export let isStreaming = false;

	const i18n = getContext('i18n');
	const dispatch = createEventDispatcher();
	let scroller: HTMLDivElement;
	let showJump = false;
	let highlighted = '';
	let previousCount = 0;

	const parseMaybeJson = (value) => {
		if (typeof value !== 'string') return value;
		try {
			return JSON.parse(value);
		} catch {
			try {
				return JSON.parse(value.replaceAll("'", '"'));
			} catch {
				return null;
			}
		}
	};

	const textFromOutput = (item) =>
		(item?.output ?? []).map((part) => part.text ?? '').join('');

	const chartFromPair = (call, result, messageId) => {
		if (call?.name !== 'render_chart') return null;
		const args = parseMaybeJson(call.arguments) ?? {};
		const text = textFromOutput(result);
		const chartId = text.match(/'chart_id': '([^']+)'/)?.[1] ?? text.match(/"chart_id": "([^"]+)"/)?.[1];
		const url = text.match(/'url': '([^']+)'/)?.[1] ?? text.match(/"url": "([^"]+)"/)?.[1];
		if (!chartId || !url) return null;
		return {
			chartId,
			url,
			messageId,
			title: args.title ?? 'Rendered chart',
			chartType: args.chart_type ?? 'chart',
			datasetId: args.dataset_context ?? '',
			fields: args.fields_used ?? `${args.x ?? ''}${args.y ? `, ${args.y}` : ''}`,
			method: args.transformation_summary ?? '',
			notes: args.explanation_notes ?? ''
		};
	};

	$: cards = messages.flatMap((message) => {
		const output = message.output ?? [];
		const results = new Map(output.filter((item) => item.type === 'function_call_output').map((item) => [item.call_id, item]));
		return output
			.filter((item) => item.type === 'function_call')
			.map((call) => chartFromPair(call, results.get(call.call_id), message.id))
			.filter(Boolean);
	});

	onMount(() => {
		const off = workspaceEvents.on('focusCanvasCard', ({ attachmentId }) => {
			const target = document.getElementById(`chart-${attachmentId}`);
			target?.scrollIntoView({ behavior: 'smooth', block: 'center' });
			highlighted = attachmentId;
			setTimeout(() => {
				if (highlighted === attachmentId) highlighted = '';
			}, 1500);
		});
		return off;
	});

	afterUpdate(() => {
		if (!scroller || cards.length === previousCount) return;
		const shouldStick = isNearBottom(scroller, 200) || previousCount === 0;
		previousCount = cards.length;
		const newest = cards.at(-1);
		if (newest) dispatch('chart-rendered', newest);
		if (shouldStick) scrollToBottom(scroller);
		else showJump = true;
	});
</script>

<section class="canvas">
	<header>
		<div>
			<h2>{$i18n.t('Analysis Canvas')}</h2>
			<p>{cards.length} {$i18n.t('charts')}</p>
		</div>
		{#if isStreaming}<span>{$i18n.t('Streaming')}</span>{/if}
	</header>

	<div bind:this={scroller} class="feed">
		{#if cards.length === 0}
			<div class="empty">{$i18n.t('Charts generated by render_chart will appear here.')}</div>
		{:else}
			{#each cards as card (card.chartId)}
				<ChartCardCanvas {card} highlighted={highlighted === card.chartId} />
			{/each}
		{/if}
	</div>

	{#if showJump}
		<button class="jump" type="button" on:click={() => { scrollToBottom(scroller); showJump = false; }}>
			{$i18n.t('New charts')}
		</button>
	{/if}
</section>

<style>
	.canvas {
		block-size: 100%;
		display: grid;
		grid-template-rows: auto minmax(0, 1fr);
		position: relative;
	}

	header {
		min-block-size: 64px;
		padding: 14px 18px;
		display: flex;
		justify-content: space-between;
		align-items: center;
		border-block-end: 1px solid var(--da-border);
		background: var(--da-panel);
	}

	h2,
	p {
		margin: 0;
	}

	h2 {
		font-size: 16px;
		font-weight: 700;
	}

	p,
	header span {
		color: var(--da-text-muted);
		font-size: 12px;
	}

	.feed {
		overflow: auto;
		padding: 18px;
		display: grid;
		align-content: start;
		gap: 14px;
	}

	.empty {
		border: 1px dashed var(--da-border);
		border-radius: var(--da-radius);
		background: var(--da-panel);
		color: var(--da-text-muted);
		padding: 28px;
		font-size: 14px;
	}

	.jump {
		position: absolute;
		inset-inline: 0;
		margin: auto;
		inset-block-end: 18px;
		inline-size: max-content;
		border: 1px solid var(--da-accent);
		background: var(--da-accent);
		color: var(--da-panel);
		border-radius: 999px;
		padding: 8px 12px;
	}
</style>
